"use client"

import { FileSpreadsheet, Printer, Download, CalendarDays } from "lucide-react"
import { useState } from "react"
import { useErp } from "@/components/erp-provider"
import { formatRupiah } from "@/lib/erp-data"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { toast } from "sonner"
export default function AccountingReportPage() { const { totalPemasukan, totalPengeluaran, labaRugi, kas } = useErp(); const [period, setPeriod] = useState("Bulanan"); const report = (name: string) => toast.success(`${name} ${period} siap diekspor`); return <div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-wider text-primary">Finance Control</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Accounting Report</h1><p className="mt-1 text-sm text-muted-foreground">Laporan formal untuk evaluasi kinerja dan pengambilan keputusan.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => report("Export PDF")}><Download className="size-4" /> PDF</Button><Button variant="outline" size="sm" onClick={() => report("Export Excel")}><FileSpreadsheet className="size-4" /> Excel</Button><Button variant="outline" size="sm" onClick={() => report("Print")}><Printer className="size-4" /> Print</Button></div></div><Tabs value={period} onValueChange={setPeriod}><TabsList><TabsTrigger value="Bulanan">Bulanan</TabsTrigger><TabsTrigger value="Kuartal">Kuartal</TabsTrigger><TabsTrigger value="Tahunan">Tahunan</TabsTrigger></TabsList><TabsContent value={period} className="mt-4 space-y-4"><div className="flex items-center gap-2 text-sm text-muted-foreground"><CalendarDays className="size-4" /> Periode: <span className="font-medium text-foreground">Juni 2026 · {period}</span></div><div className="grid gap-4 sm:grid-cols-3"><Metric title="Pendapatan" value={formatRupiah(totalPemasukan)} tone="text-accent"/><Metric title="Beban Operasional" value={formatRupiah(totalPengeluaran)} tone="text-destructive"/><Metric title="Laba Bersih" value={formatRupiah(labaRugi)} tone="text-primary"/></div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Laba Rugi</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Line label="Pendapatan Penjualan" value={formatRupiah(totalPemasukan)} /><Line label="Beban Operasional" value={formatRupiah(totalPengeluaran)} /><div className="border-t pt-3"><Line label="Laba Bersih" value={formatRupiah(labaRugi)} bold /></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Arus Kas</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{kas.slice(0, 5).map((item) => <Line key={item.id_kas} label={item.keterangan} value={`${item.jenis === "Masuk" ? "+" : "-"}${formatRupiah(item.jumlah)}`} />)}</CardContent></Card></div></TabsContent></Tabs></div> }
function Metric({ title, value, tone }: { title: string; value: string; tone: string }) { return <Card className="p-5"><p className="text-xs text-muted-foreground">{title}</p><p className={`mt-2 text-xl font-semibold ${tone}`}>{value}</p></Card> }
function Line({ label, value, bold }: { label: string; value: string; bold?: boolean }) { return <div className="flex justify-between gap-4"><span className={bold ? "font-semibold" : "text-muted-foreground"}>{label}</span><span className={bold ? "font-semibold" : "font-medium"}>{value}</span></div> }
